# Generated by Django 5.2.8 on 2025-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avgreview', models.FloatField(default=0.0)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
    ]
